<?php
/**
 * @file
 * An example of how to use the new #states Form API element, allowing dynamic form behavior with very simple setup.
 */
/**
 * Implements hook_menu().
 */ 
function dynamic_menu() {
  $items['dynamic'] = array(
    'title' => t('Form Example Dynamic Form'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('dynamic_form'),
    'file' => 'dynamic.admin.inc',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['demo'] = array(
    'title' => t('Ajax demo'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('automobile_dependent_dropdown'),
    'file' => 'dynamic.admin.inc',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['more'] = array(
    'title' => t('More demo'),
    'page callback' => 'drupal_get_form',
    'page arguments' => array('more_test_form'),
    'file' => 'dynamic.admin.inc',
    'access callback' => TRUE,
    'type' => MENU_NORMAL_ITEM,
  );
  $items['cities/autocomplete'] = array(
    'title' => 'Autocomplete for cities',
    'page callback' => '_cities_autocomplete',
    //'access arguments' => array('),
    'type' => MENU_CALLBACK,
  );
  return $items;
}
